"""
URL mappings for the recipe app.
"""
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from recipe import views

#  Create the router
router = DefaultRouter()

# Register our ViewSet with the router
# This automatically assigns the '/recipes/' and '/recipes/<id>/' endpoints
router.register('recipes', views.RecipeViewSet)
# Define the app name so the reverse() function in our tests can find it
app_name = 'recipe'

urlpatterns = [
    # Include all the URLs generated by the router
    path('', include(router.urls)),
]