"""
URL mappings for the recipe app.
"""
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from recipe import views

#  Create the router
router = DefaultRouter()


router.register('recipes', views.RecipeViewSet)
router.register('tags', views.TagViewSet)
router.register('ingredients', views.IngredientViewSet)

app_name = 'recipe'

urlpatterns = [
    # Include all the URLs generated by the router
    path('', include(router.urls)),
]